### ISSUE TITLE
菜单可以设置左侧和顶闻这个功能很棒。建议：在顶部时，如果固定住，会更好。

### ISSUE THREAD

**Issue by tryrefine** [huzzbuzz/bear-admin#2]
另外，菜单在左侧时，也希望顶部的带“设置”功能的导航菜单固定住。

**Comment by huzzbuzz** [comment]
@tryrefine 感谢建议，有时间我看看哈~

**Comment by tryrefine** [comment]
好的，感谢这么快就响应。另外，能不能建个 qq 群，大家好一起讨论交流。

**Comment by tryrefine** [comment]
@huzzbuzz 顶部菜单，固定与否，通过配置来决定。就象你另外一个项目，显示或者不显示菜单的背景那样。这样的话，就更高大上了。

**Comment by huzzbuzz** [comment]
@tryrefine 精力有限，暂时就不建群了 :disappointed_relieved: :disappointed_relieved:  以上我看看先加到 to do list

**Comment by tryrefine** [comment]
@huzzbuzz 嗯嗯，理解

**Comment by huzzbuzz** [comment]
Issues 就先关了，已加到 #1
